### ISSUE TITLE
Server Plugin\bin\*.dll missing

### ISSUE THREAD

**Issue by foobarto** [huhlig/empyrion-python-api#1]
Hey @huhlig kudos for making python modding for Empyrion happen!
However looking at your instructions in README the Server Plugin\bin folder is missing.

**Comment by huhlig** [comment]
The bin directory is created when you build the solution.

**Comment by foobarto** [comment]
d'oh, got it, thanks! VStudio is much more intuitive than I remembered.
Not a .NET developer here, obviously :)
